'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ArrowUpRight,Check,ImagePlus,Leaf,Monitor,Smartphone,Save,Eye,X,Upload,LayoutList} from 'lucide-react';
import {fields,freshContent,sectionNames,validateContent,type SiteContent} from '../../lib/cms';
import {contentRepository,assetStorage,adminAuth} from '../../lib/cms-repository';
import './admin.css';
function TextField({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="cms-field"><span>{label}</span>{multiline?<textarea value={value} rows={3} maxLength={5000} onChange={e=>onChange(e.target.value)}/>:<input value={value} maxLength={5000} onChange={e=>onChange(e.target.value)}/>}</label>;}
function ImageField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="cms-image-field"><img src={value} alt={label}/><div><h3>{label}</h3><label className="cms-upload"><ImagePlus size={17}/>{busy?'Đang xử lý ảnh…':'Tải ảnh thay thế'}<input aria-label={`Tải ảnh: ${label}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{onChange(await assetStorage.upload(file));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label><p>JPG, PNG, WebP · tối đa 10 MB</p><TextField label="Đường dẫn ảnh" value={value.startsWith('data:')?'':value} onChange={onChange}/>{value.startsWith('data:')&&<small>Đã chọn ảnh tải lên</small>}{error&&<p role="alert" className="cms-error">{error}</p>}</div></div>;}
export default function Admin(){
 const [data,setData]=useState<SiteContent>(freshContent),[active,setActive]=useState('hero'),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[publishedAt,setPublishedAt]=useState<string|null>(null),[preview,setPreview]=useState(false),[mobile,setMobile]=useState(false),[previewKey,setPreviewKey]=useState(0);const dialog=useRef<HTMLDialogElement>(null),previewTrigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{Promise.all([contentRepository.load(),adminAuth.getSession()]).then(([state,session])=>{if(!session)throw new Error('Phiên quản trị chưa sẵn sàng.');setData(state.draft);setPublishedAt(state.publishedAt);setReady(true);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(preview){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[preview]);
 function edit(fn:(draft:SiteContent)=>void){setData(prev=>{const next=JSON.parse(JSON.stringify(prev)) as SiteContent;fn(next);return next;});setDirty(true);setNotice('');setError('');}
 async function save(){setBusy(true);setError('');try{validateContent(data);await contentRepository.saveDraft(data);setDirty(false);setNotice('Đã lưu bản nháp. Trang chính chưa thay đổi.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function openPreview(){if(await save()){setPreviewKey(k=>k+1);setPreview(true);}}
 async function publish(){setBusy(true);setError('');try{await contentRepository.publish(data);setPublishedAt(new Date().toISOString());setDirty(false);setNotice('Đã xuất bản trên trình duyệt này. Mở trang chính để xem thay đổi.');setPreview(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function move(index:number,delta:number){edit(d=>{const target=index+delta;[d.order[index],d.order[target]]=[d.order[target],d.order[index]];});}
 const copyFields=fields.filter(f=>f.group===active);
 return <div className="cms-shell"><aside className="cms-sidebar"><a href="/" className="cms-brand"><span><Leaf size={23}/></span><div>NGỌC ĐỒNG<small>QUẢN TRỊ NỘI DUNG</small></div></a><div className="cms-sidebar-title"><LayoutList size={16}/> NỘI DUNG TRANG</div><nav aria-label="Các phần nội dung">{data.order.map((id,i)=><div className={`cms-nav-row ${active===id?'active':''}`} key={id}><button aria-current={active===id?'page':undefined} onClick={()=>setActive(id)}><span>{String(i+1).padStart(2,'0')}</span>{sectionNames[id]}</button>{i>0&&<div className="cms-order"><button aria-label={`Đưa ${sectionNames[id]} lên`} disabled={i===1||!ready} onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button aria-label={`Đưa ${sectionNames[id]} xuống`} disabled={i===data.order.length-1||!ready} onClick={()=>move(i,1)}><ArrowDown size={14}/></button></div>}</div>)}</nav><p className="cms-order-help">Dùng ↑ ↓ để sắp xếp các phần.<br/>Ảnh bìa luôn ở đầu trang.</p><div className="cms-sidebar-title">THIẾT LẬP CHUNG</div>{['images','header','footer','general'].map(id=><button className={`cms-extra ${active===id?'active':''}`} key={id} onClick={()=>setActive(id)}>{id==='images'?'Ảnh dùng chung':sectionNames[id]}</button>)}<a className="cms-site-link" href="/" target="_blank" rel="noreferrer">Mở trang chính <ArrowUpRight size={17}/></a></aside>
 <div className="cms-main"><header className="cms-toolbar"><div><span className="cms-breadcrumb">Website / Nội dung</span><h1>Chăm chút từng điều nhỏ.</h1></div><div className="cms-actions"><button disabled={!ready||busy} onClick={save}><Save size={17}/><span>Lưu nháp</span></button><button ref={previewTrigger} className="primary" disabled={!ready||busy} onClick={openPreview}><Eye size={17}/><span>Xem trước & xuất bản</span></button></div></header>
 <div className="cms-local-note"><span className="cms-demo-badge">BẢN THỬ</span><p>Nội dung và ảnh được lưu trên trình duyệt này. “Xuất bản” cập nhật trang chính tại đây, chưa đồng bộ sang thiết bị khác.</p></div>
 <div className="cms-content"><div className="cms-title-row"><div><p className="cms-kicker">BIÊN TẬP NỘI DUNG</p><h2>{active==='images'?'Ảnh dùng chung':sectionNames[active]}</h2></div><span className={`cms-status ${dirty?'unsaved':''}`}><Check size={15}/>{dirty?'Có thay đổi chưa lưu':'Bản nháp đã sẵn sàng'}</span></div>
 <p className="cms-help">Sửa nội dung bên dưới, lưu nháp rồi xem trước để kiểm tra bố cục.</p>
 {notice&&<p role="status" className="cms-success">{notice}</p>}{error&&<p role="alert" className="cms-error">{error}</p>}
 {!ready?<p>Đang mở nội dung…</p>:<fieldset className="cms-editor" disabled={busy}>
 {active==='hero'&&<TextField label="Mô tả ảnh bìa" value={data.heroAlt} onChange={v=>edit(d=>{d.heroAlt=v;})}/>}
 {active==='hero'&&<ImageField label="Ảnh bìa trang chủ" value={data.media.hero.image} onChange={v=>edit(d=>{d.media.hero.image=v;})}/>}
 {active==='images'&&<><p className="cms-help">Ảnh dùng chung xuất hiện ở phần giới thiệu, Long Cốc và kỳ nghỉ cho hai. Phòng nghỉ, câu chuyện và thư viện có ảnh riêng trong từng mục.</p>{(['tea','room'] as const).map((key)=><ImageField key={key} label={{tea:'Tách trà',room:'Không gian nghỉ',pool:'Hồ bơi'}[key]} value={data.media[key]} onChange={v=>edit(d=>{d.media[key]=v;})}/>)}</>}
 {copyFields.length>0&&<section className="cms-card"><h3>Văn bản & nút bấm</h3>{copyFields.map((f,i)=><TextField key={f.key} label={active==='hero'?f.label:`${f.label} ${i+1}`} value={data.copy[f.key]} multiline={f.value.length>70} onChange={v=>edit(d=>{d.copy[f.key]=v;})}/>)}</section>}
 {active==='hero'&&<section className="cms-card"><TextField label="Đích đến các nút đặt phòng" value={data.cta.href} onChange={v=>edit(d=>{d.cta.href=v;})}/><p className="cms-help">Ví dụ: #booking, tel:0965163291 hoặc một địa chỉ https://…</p></section>}
 {active==='booking'&&<section className="cms-card"><h3>Thông tin liên hệ</h3><TextField label="Số điện thoại" value={data.contact.phone} onChange={v=>edit(d=>{d.contact.phone=v;})}/><TextField label="Liên kết Zalo" value={data.contact.zalo} onChange={v=>edit(d=>{d.contact.zalo=v;})}/></section>}
 {active==='location'&&<section className="cms-card"><TextField label="Địa chỉ Làng (cũng dùng cho bản đồ & cuối trang)" value={data.address} onChange={v=>edit(d=>{d.address=v;})}/></section>}
 {active==='rooms'&&data.rooms.map((r,i)=><section className="cms-card" key={i}><h3>Phòng {i+1}</h3><ImageField label={`Ảnh phòng ${i+1}`} value={r.image} onChange={v=>edit(d=>{d.rooms[i].image=v;})}/>{(['name','tag','text','capacity','price'] as const).map(k=><TextField key={k} label={{name:'Tên phòng',tag:'Dòng giới thiệu',text:'Mô tả phòng',capacity:'Sức chứa',price:'Giá hiển thị'}[k]} value={r[k]} multiline={k==='text'} onChange={v=>edit(d=>{d.rooms[i][k]=v;})}/>)}</section>)}
 {active==='experiences'&&data.experiences.map((r,i)=><section className="cms-card" key={i}><h3>Trải nghiệm {i+1}</h3><TextField label="Tên trải nghiệm / dịch vụ" value={r.title} onChange={v=>edit(d=>{d.experiences[i].title=v;})}/><TextField label="Mô tả" value={r.text} multiline onChange={v=>edit(d=>{d.experiences[i].text=v;})}/></section>)}
 {active==='story'&&data.scenes.map((r,i)=><section className="cms-card" key={r.id}><h3>Khoảnh khắc {i+1}</h3><ImageField label={`Ảnh khoảnh khắc ${i+1}`} value={r.image} onChange={v=>edit(d=>{d.scenes[i].image=v;})}/>{(['time','title','text'] as const).map(k=><TextField key={k} label={{time:'Thời điểm · tên khoảnh khắc',title:'Tiêu đề',text:'Mô tả'}[k]} value={r[k]} multiline={k==='text'} onChange={v=>edit(d=>{d.scenes[i][k]=v;})}/>)}</section>)}
 {active==='gallery'&&data.gallery.map((r,i)=><section className="cms-card" key={i}><ImageField label={`Ảnh thư viện ${i+1}`} value={r.src} onChange={v=>edit(d=>{d.gallery[i].src=v;})}/><TextField label="Chú thích" value={r.caption} onChange={v=>edit(d=>{d.gallery[i].caption=v;})}/><TextField label="Mô tả ảnh cho trình đọc màn hình" value={r.alt} onChange={v=>edit(d=>{d.gallery[i].alt=v;})}/></section>)}
 </fieldset>}
 <div className="cms-bottom"><span>{publishedAt?`Xuất bản gần nhất: ${new Date(publishedAt).toLocaleString('vi-VN')}`:'Chưa có thay đổi được xuất bản'}</span><a href="/" target="_blank" rel="noreferrer">Xem trang chính ↗</a></div></div></div>
 <dialog className="cms-preview-dialog" ref={dialog} onCancel={()=>setPreview(false)} onClose={()=>{setPreview(false);previewTrigger.current?.focus();}}><div className="cms-preview-toolbar"><div><strong>Xem trước bản nháp</strong><small>Kiểm tra nội dung trước khi xuất bản trên trình duyệt này.</small></div><div className="cms-preview-actions"><button aria-label="Xem trên máy tính" aria-pressed={!mobile} onClick={()=>setMobile(false)}><Monitor size={20}/></button><button aria-label="Xem trên điện thoại" aria-pressed={mobile} onClick={()=>setMobile(true)}><Smartphone size={20}/></button><button className="primary" disabled={busy} onClick={publish}><Upload size={17}/>Xuất bản</button><button aria-label="Đóng xem trước" onClick={()=>setPreview(false)}><X size={20}/></button></div></div>{error&&<p role="alert" className="cms-error">{error}</p>}<div className="cms-preview-stage">{preview&&<iframe key={previewKey} title="Bản xem trước website" src="/preview/" style={{width:mobile?'390px':'100%'}}/>}</div></dialog>
 </div>;
}
