'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ArrowUpRight,Check,ImagePlus,Leaf,Monitor,Smartphone,Save,Eye,X,Upload,LayoutList} from 'lucide-react';
import {fields,freshContent,migrateContent,sectionNames,validateContent,type SiteContent} from '../../lib/cms';
import {contentRepository,assetStorage,adminAuth} from '../../lib/cms-repository';
import {imageSlots,linkFields} from '../../lib/cms-options';
import './admin.css';
function TextField({label,value,onChange,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <label className="cms-field"><span>{label}</span>{multiline?<textarea value={value} rows={3} maxLength={5000} onChange={e=>onChange(e.target.value)}/>:<input value={value} maxLength={5000} onChange={e=>onChange(e.target.value)}/>}</label>;}
function ImageField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <div className="cms-image-field">{value?<img src={value} alt={label}/>:<div className="cms-empty-image">Chưa chọn ảnh</div>}<div><h3>{label}</h3><label className="cms-upload"><ImagePlus size={17}/>{busy?'Đang xử lý ảnh…':'Tải ảnh thay thế'}<input aria-label={`Tải ảnh: ${label}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{onChange(await assetStorage.upload(file));}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label><p>JPG, PNG, WebP · tối đa 10 MB</p><TextField label="Đường dẫn ảnh" value={value.startsWith('data:')?'':value} onChange={onChange}/>{value.startsWith('data:')&&<small>Đã chọn ảnh tải lên</small>}{error&&<p role="alert" className="cms-error">{error}</p>}</div></div>;}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="cms-checkbox"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export default function Admin(){
 const [data,setData]=useState<SiteContent>(freshContent),[active,setActive]=useState('hero'),[query,setQuery]=useState(''),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[publishedAt,setPublishedAt]=useState<string|null>(null),[preview,setPreview]=useState(false),[mobile,setMobile]=useState(false),[previewKey,setPreviewKey]=useState(0),[previewPath,setPreviewPath]=useState('/preview/'),[legacy,setLegacy]=useState(false);const dialog=useRef<HTMLDialogElement>(null),previewTrigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{Promise.all([contentRepository.load(),adminAuth.getSession()]).then(([state,session])=>{if(!session)throw new Error('Phiên quản trị chưa sẵn sàng.');setData(state.draft);setPublishedAt(state.publishedAt);setReady(true);setLegacy(!!localStorage.getItem('ngoc-dong-cms-v1'));}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(preview){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[preview]);
 function edit(fn:(draft:SiteContent)=>void){setData(prev=>{const next=JSON.parse(JSON.stringify(prev)) as SiteContent;fn(next);return next;});setDirty(true);setNotice('');setError('');}
 async function save(){setBusy(true);setError('');try{validateContent(data);await contentRepository.saveDraft(data);setDirty(false);setNotice('Đã lưu bản nháp. Trang chính chưa thay đổi.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function openPreview(path='/preview/'){if(await save()){setPreviewPath(path);setPreviewKey(k=>k+1);setPreview(true);}}
 async function publish(){setBusy(true);setError('');try{await contentRepository.publish(data);setPublishedAt(new Date().toISOString());setDirty(false);setNotice('Đã xuất bản. Nội dung mới đã được lưu chung cho mọi khách truy cập website.');setPreview(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function removeItem(key:'rooms'|'experiences'|'gallery'|'posts'|'navigation',index:number,name:string){if(window.confirm(`Xóa “${name}” khỏi bản nháp? Website chỉ đổi sau khi xuất bản.`))edit(d=>{d[key].splice(index,1);});}
 function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ngoc-dong-noi-dung-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importContent(raw:unknown){try{async function images(value:any):Promise<any>{if(typeof value==='string'&&value.startsWith('data:image/')){const blob=await(await fetch(value)).blob();return assetStorage.upload(new File([blob],'anh-cu.jpg',{type:blob.type}));}if(Array.isArray(value))return Promise.all(value.map(images));if(value&&typeof value==='object'){const result:any={};for(const [key,item]of Object.entries(value))result[key]=await images(item);return result;}return value;}setBusy(true);const next=migrateContent(await images(raw));validateContent(next);setData(next);setDirty(true);setNotice('Đã nạp vào form. Hãy kiểm tra, lưu nháp và xem trước trước khi xuất bản.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function move(index:number,delta:number){edit(d=>{const target=index+delta;[d.order[index],d.order[target]]=[d.order[target],d.order[index]];});}
 const copyFields=fields.filter(f=>f.group===active&&f.key!=='rooms_7');
 const queryText=query.trim().toLocaleLowerCase('vi');
 const results=Object.entries(sectionNames).filter(([id,name])=>{
 const values=[name,...fields.filter(f=>f.group===id).map(f=>data.copy[f.key]),...imageSlots.filter(f=>f.group===id).map(f=>f.label),...linkFields.filter(f=>f.group===id).map(f=>f.label)];
 if(id==='blog')values.push(...data.posts.flatMap(p=>[p.title,p.excerpt,p.body]));
 if(id==='rooms')values.push(...data.rooms.flatMap(r=>[r.name,r.text,r.price,r.capacity,r.alt,r.ctaLabel]));
 if(id==='story')values.push(...data.scenes.flatMap(r=>[r.title,r.text,r.time,r.credit,r.navLabel]));
 if(id==='experiences')values.push(...data.experiences.flatMap(r=>[r.title,r.text]));
 if(id==='gallery')values.push(...data.gallery.flatMap(r=>[r.caption,r.alt]));
 if(id==='header')values.push(...data.navigation.map(r=>r.label));
 return queryText&&values.some(v=>v?.toLocaleLowerCase('vi').includes(queryText));});
 return <div className="cms-shell"><aside className="cms-sidebar"><a href="/" className="cms-brand"><span><Leaf size={23}/></span><div>NGỌC ĐỒNG<small>QUẢN TRỊ NỘI DUNG</small></div></a><label className="cms-mobile-select">Chọn nội dung cần sửa<select aria-label="Chọn nội dung cần sửa" value={active} onChange={e=>setActive(e.target.value)}>{[...data.order,'blog','header','footer','seo','general'].map(id=><option key={id} value={id}>{sectionNames[id]}</option>)}</select></label><div className="cms-sidebar-title"><LayoutList size={16}/> NỘI DUNG TRANG</div><nav aria-label="Các phần nội dung">{data.order.map((id,i)=><div className={`cms-nav-row ${active===id?'active':''}`} key={id}><button aria-current={active===id?'page':undefined} onClick={()=>setActive(id)}><span>{String(i+1).padStart(2,'0')}</span>{sectionNames[id]}</button>{i>0&&<div className="cms-order"><button aria-label={`Đưa ${sectionNames[id]} lên`} disabled={i===1||!ready} onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button aria-label={`Đưa ${sectionNames[id]} xuống`} disabled={i===data.order.length-1||!ready} onClick={()=>move(i,1)}><ArrowDown size={14}/></button></div>}</div>)}</nav><p className="cms-order-help">Dùng ↑ ↓ để sắp xếp các phần.<br/>Ảnh bìa luôn ở đầu trang.</p><div className="cms-sidebar-title">THIẾT LẬP CHUNG</div>{['blog','header','footer','seo','general'].map(id=><button className={`cms-extra ${active===id?'active':''}`} key={id} onClick={()=>setActive(id)}>{id==='images'?'Ảnh dùng chung':sectionNames[id]}</button>)}<a className="cms-site-link" href="/" target="_blank" rel="noreferrer">Mở trang chính <ArrowUpRight size={17}/></a></aside>
 <div className="cms-main"><header className="cms-toolbar"><div><span className="cms-breadcrumb">Website / Nội dung</span><h1>Quản trị website Ngọc Đồng</h1></div><div className="cms-actions"><button disabled={!ready||busy} onClick={save}><Save size={17}/><span>Lưu nháp</span></button><button ref={previewTrigger} className="primary" disabled={!ready||busy} onClick={()=>openPreview()}><Eye size={17}/><span>Xem trước & xuất bản</span></button></div></header>
 <div className="cms-local-note"><span className="cms-demo-badge">LƯU TRỰC TUYẾN</span><p>Lưu nháp để giữ thay đổi riêng. Xem trước và xuất bản khi anh đã sẵn sàng cập nhật website.</p></div>
 <div className="cms-content"><div className="cms-search"><label className="cms-field"><span>Tìm phần cần sửa theo chữ đang thấy trên website</span><input type="search" placeholder="Ví dụ: bình yên, đồi chè, căn phòng…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{queryText&&<div className="cms-search-results" aria-live="polite">{results.length?results.map(([id,name])=><button key={id} onClick={()=>{setActive(id);setQuery('');}}>{name}<ArrowUpRight size={15}/></button>):<p>Không tìm thấy nội dung phù hợp.</p>}</div>}</div><div className="cms-title-row"><div><p className="cms-kicker">BIÊN TẬP NỘI DUNG</p><h2>{active==='images'?'Ảnh dùng chung':sectionNames[active]}</h2></div><span className={`cms-status ${dirty?'unsaved':''}`}><Check size={15}/>{dirty?'Có thay đổi chưa lưu':'Bản nháp đã sẵn sàng'}</span></div>
 <p className="cms-help">Sửa nội dung bên dưới, lưu nháp rồi xem trước để kiểm tra bố cục.</p>
 {notice&&<p role="status" className="cms-success">{notice}</p>}{error&&<p role="alert" className="cms-error">{error}</p>}
 {!ready?<p>{error?'Chưa mở được nội dung.':'Đang mở nội dung…'} {error&&<a href="/signin-with-chatgpt?return_to=%2Fadmin%2F" target="_top">Đăng nhập quản trị</a>}</p>:<fieldset className="cms-editor" disabled={busy}>
 {active==='hero'&&<TextField label="Mô tả ảnh bìa" value={data.heroAlt} onChange={v=>edit(d=>{d.heroAlt=v;})}/>}
 {active==='hero'&&<ImageField label="Ảnh bìa trang chủ" value={data.media.hero.image} onChange={v=>edit(d=>{d.media.hero.image=v;})}/>}
 {imageSlots.filter(f=>f.group===active).map(f=><section className="cms-card" key={f.key}><ImageField label={f.label} value={data.images[f.key].image} onChange={v=>edit(d=>{d.images[f.key].image=v;})}/><TextField label={`Mô tả ${f.label.toLocaleLowerCase('vi')}`} value={data.images[f.key].alt} onChange={v=>edit(d=>{d.images[f.key].alt=v;})}/></section>)}
 {active==='header'&&<section className="cms-card"><h3>Menu trên máy tính & điện thoại</h3><button onClick={()=>edit(d=>{d.navigation.push({label:'Mục mới',href:'/blog/'});})}>Thêm mục menu</button>{data.navigation.map((n,i)=><div className="cms-menu-item" key={i}><button onClick={()=>removeItem('navigation',i,n.label)}>Xóa mục menu {i+1}</button><TextField label={`Tên mục menu ${i+1}`} value={n.label} onChange={v=>edit(d=>{d.navigation[i].label=v;})}/><TextField label={`Liên kết mục menu ${i+1}`} value={n.href} onChange={v=>edit(d=>{d.navigation[i].href=v;})}/></div>)}</section>}
 {linkFields.some(f=>f.group===active)&&<section className="cms-card"><h3>Liên kết nút bấm</h3>{linkFields.filter(f=>f.group===active).map(f=><TextField key={f.key} label={f.label} value={data.links[f.key]} onChange={v=>edit(d=>{d.links[f.key]=v;})}/>)}<p className="cms-help">Dùng #booking, #rooms, số gọi tel:… hoặc đường dẫn https://…</p></section>}
 {copyFields.length>0&&<section className="cms-card"><h3>Văn bản & nút bấm</h3>{copyFields.map((f,i)=><TextField key={f.key} label={active==='hero'?f.label:`${f.label} — ${f.value.trim().slice(0,65)}`} value={data.copy[f.key]} multiline={f.value.length>70} onChange={v=>edit(d=>{d.copy[f.key]=v;})}/>)}</section>}

 {active==='booking'&&<section className="cms-card"><h3>Thông tin liên hệ</h3><TextField label="Số điện thoại" value={data.contact.phone} onChange={v=>edit(d=>{d.contact.phone=v;})}/><TextField label="Liên kết Zalo" value={data.contact.zalo} onChange={v=>edit(d=>{d.contact.zalo=v;})}/></section>}
 {active==='location'&&<section className="cms-card"><TextField label="Địa chỉ Làng (cũng dùng cho bản đồ & cuối trang)" value={data.address} onChange={v=>edit(d=>{d.address=v;})}/></section>}
 {active==='rooms'&&data.rooms.map((r,i)=><section className="cms-card" key={i}><div className="cms-item-heading"><h3>Phòng {i+1}</h3><button onClick={()=>removeItem('rooms',i,r.name)}>Xóa phòng</button></div><ImageField label={`Ảnh phòng ${i+1}`} value={r.image} onChange={v=>edit(d=>{d.rooms[i].image=v;})}/><Toggle label="Hiện nhãn ảnh minh họa cho phòng này" value={r.illustrative} onChange={v=>edit(d=>{d.rooms[i].illustrative=v;})}/>{(['name','tag','text','capacity','price','amenities','alt','ctaLabel','ctaHref'] as const).map(k=><TextField key={k} label={{name:'Tên phòng',tag:'Dòng giới thiệu',text:'Mô tả phòng',capacity:'Sức chứa',price:'Giá hiển thị',amenities:'Tiện nghi (mỗi tiện nghi một dòng)',alt:'Mô tả ảnh phòng',ctaLabel:'Nhãn nút của phòng',ctaHref:'Liên kết nút của phòng'}[k]} value={r[k]} multiline={k==='text'||k==='amenities'} onChange={v=>edit(d=>{d.rooms[i][k]=v;})}/>)}</section>)}
 {active==='experiences'&&data.experiences.map((r,i)=><section className="cms-card" key={i}><div className="cms-item-heading"><h3>Trải nghiệm {i+1}</h3><button onClick={()=>removeItem('experiences',i,r.title)}>Xóa dịch vụ</button></div><TextField label="Tên trải nghiệm / dịch vụ" value={r.title} onChange={v=>edit(d=>{d.experiences[i].title=v;})}/><TextField label="Mô tả" value={r.text} multiline onChange={v=>edit(d=>{d.experiences[i].text=v;})}/></section>)}
 {active==='story'&&data.scenes.map((r,i)=><section className="cms-card" key={r.id}><h3>Khoảnh khắc {i+1}</h3><ImageField label={`Ảnh khoảnh khắc ${i+1}`} value={r.image} onChange={v=>edit(d=>{d.scenes[i].image=v;})}/>{(['time','title','text','navLabel','credit','alt'] as const).map(k=><TextField key={k} label={{time:'Thời điểm · tên khoảnh khắc',title:'Tiêu đề',text:'Mô tả',navLabel:'Tên trên thanh chọn khoảnh khắc',credit:'Chú thích / nguồn ảnh',alt:'Mô tả ảnh khoảnh khắc'}[k]} value={r[k]} multiline={k==='text'} onChange={v=>edit(d=>{d.scenes[i][k]=v;})}/>)}</section>)}
 {active==='gallery'&&data.gallery.map((r,i)=><section className="cms-card" key={i}><div className="cms-item-heading"><h3>Ảnh {i+1}</h3><button onClick={()=>removeItem('gallery',i,r.caption)}>Xóa ảnh</button></div><ImageField label={`Ảnh thư viện ${i+1}`} value={r.src} onChange={v=>edit(d=>{d.gallery[i].src=v;})}/><Toggle label="Hiện nhãn ảnh minh họa trong thư viện" value={r.illustrative} onChange={v=>edit(d=>{d.gallery[i].illustrative=v;})}/><TextField label="Chú thích" value={r.caption} onChange={v=>edit(d=>{d.gallery[i].caption=v;})}/><TextField label="Mô tả ảnh cho trình đọc màn hình" value={r.alt} onChange={v=>edit(d=>{d.gallery[i].alt=v;})}/></section>)}

 {active==='booking'&&<section className="cms-card"><h3>Các kênh liên hệ khác</h3><p className="cms-help">Để trống nếu chưa có. Chỉ các kênh đã điền mới xuất hiện trên website.</p>{(['facebook','googleMaps','booking','whatsapp'] as const).map(k=><TextField key={k} label={{facebook:'Facebook',googleMaps:'Google Maps — liên kết ghim chính xác',booking:'Booking',whatsapp:'WhatsApp'}[k]} value={data.contact[k]} onChange={v=>edit(d=>{d.contact[k]=v;})}/>)}</section>}
 {active==='rooms'&&<button onClick={()=>edit(d=>{d.rooms.push({...freshContent().rooms[0],name:'Phòng mới',text:'',amenities:'',price:'Liên hệ báo giá'});})}>+ Thêm phòng nghỉ</button>}
 {active==='experiences'&&<button onClick={()=>edit(d=>{d.experiences.push({title:'Dịch vụ mới',text:''});})}>+ Thêm dịch vụ / trải nghiệm</button>}
 {active==='gallery'&&<button onClick={()=>edit(d=>{d.gallery.push({src:data.media.hero.image,alt:'Ảnh mới',caption:'Ảnh mới',illustrative:false});})}>+ Thêm ảnh vào thư viện</button>}
 {active==='seo'&&<section className="cms-card"><h3>SEO & chia sẻ mạng xã hội</h3><TextField label="Tiêu đề SEO toàn site (gợi ý 50–60 ký tự)" value={data.seo.title} onChange={v=>edit(d=>{d.seo.title=v;})}/><TextField label="Mô tả SEO toàn site (gợi ý 140–160 ký tự)" value={data.seo.description} multiline onChange={v=>edit(d=>{d.seo.description=v;})}/><TextField label="Tên miền chính thức (https://…)" value={data.seo.siteUrl} onChange={v=>edit(d=>{d.seo.siteUrl=v;})}/><ImageField label="Ảnh khi chia sẻ liên kết" value={data.seo.shareImage} onChange={v=>edit(d=>{d.seo.shareImage=v;})}/><p className="cms-help">Tiêu đề, mô tả, ảnh chia sẻ và sơ đồ website được cập nhật khi xuất bản. Thay tên miền SEO không tự đăng ký hoặc kết nối tên miền mới.</p><div className="cms-seo-preview"><strong>{data.seo.title}</strong><small>{data.seo.siteUrl}</small><p>{data.seo.description}</p></div></section>}
 {active==='blog'&&<><section className="cms-card"><h3>Bài viết của Làng</h3><p>Viết bài, thêm ảnh, đặt đường dẫn và bật “Hiển thị bài viết” khi muốn đưa bài lên website. Sau đó xem trước và xuất bản.</p><div className="cms-inline-actions"><button onClick={()=>edit(d=>{d.posts.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2),title:'Bài viết mới',slug:'bai-viet-'+Date.now(),excerpt:'',body:'',image:'',alt:'',seoTitle:'',metaDescription:'',published:false,date:new Date().toISOString().slice(0,10)});})}>+ Thêm bài viết</button><button onClick={()=>openPreview('/blog/?preview=1')}>Xem trước blog</button></div>{!data.posts.length&&<p>Chưa có bài viết. Bấm “Thêm bài viết” để bắt đầu.</p>}</section>{data.posts.map((post,i)=><section className="cms-card" key={post.id}><div className="cms-item-heading"><h3>{post.title||'Bài viết mới'}</h3><button onClick={()=>removeItem('posts',i,post.title)}>Xóa bài viết</button></div><Toggle label="Hiển thị bài viết khi xuất bản website" value={post.published} onChange={v=>edit(d=>{d.posts[i].published=v;})}/>{(['title','slug','date','excerpt','body','alt','seoTitle','metaDescription'] as const).map(k=><TextField key={k} label={{title:'Tên bài viết',slug:'Đường dẫn bài viết (slug)',date:'Ngày đăng (YYYY-MM-DD)',excerpt:'Mô tả ngắn',body:'Nội dung bài viết',alt:'Mô tả ảnh đại diện',seoTitle:'Tiêu đề SEO (để trống dùng tên bài)',metaDescription:'Mô tả SEO (để trống dùng mô tả ngắn)'}[k]} value={post[k]} multiline={['body','excerpt','metaDescription'].includes(k)} onChange={v=>edit(d=>{d.posts[i][k]=v;})}/>)}<ImageField label="Ảnh đại diện bài viết" value={post.image} onChange={v=>edit(d=>{d.posts[i].image=v;})}/><div className="cms-inline-actions"><button onClick={()=>openPreview('/blog/'+post.slug+'/?preview=1')}>Xem trước bài này</button>{post.image&&<button onClick={()=>edit(d=>{d.posts[i].image='';})}>Bỏ ảnh đại diện</button>}</div><p className="cms-help">Đường dẫn: /blog/{post.slug}/ · Nếu đổi slug của bài đã đăng, liên kết cũ sẽ không còn dùng được.</p></section>)}</>}
 {active==='general'&&<section className="cms-card"><h3>Hướng dẫn nhanh</h3><ol><li>Chọn nhóm nội dung ở menu, sửa chữ hoặc bấm “Tải ảnh thay thế”.</li><li>Bấm “Lưu nháp” để lưu riêng, khách chưa thấy thay đổi.</li><li>Bấm “Xem trước & xuất bản”, kiểm tra trên điện thoại / máy tính.</li><li>Bấm “Xuất bản” để cập nhật website cho tất cả khách truy cập.</li></ol><p>Ảnh bìa chỉ thay đổi khi anh chọn ảnh khác trong mục “Ảnh bìa & lời chào”. Ảnh upload được thu nhỏ để tải nhanh. Các phòng và ảnh minh họa cần thay bằng thông tin thật trước khi mở bán.</p><h3>Sao lưu nội dung</h3><p>Bản sao lưu gồm chữ và đường dẫn ảnh. Ảnh đã tải lên được lưu riêng trên website. Hãy tải bản sao lưu trước khi nhập lại nội dung.</p><div className="cms-inline-actions"><button onClick={backup}>Tải bản sao lưu</button><label className="cms-upload">Nhập bản sao lưu<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>20000000){setError('Bản sao lưu quá lớn.');return;}try{const raw=JSON.parse(await file.text());if(window.confirm('Nạp bản sao lưu vào form? Nội dung đang sửa sẽ được thay thế; website chưa đổi.'))await importContent(raw.draft||raw);}catch{setError('Không đọc được bản sao lưu JSON.');}}}/></label></div>{legacy&&<button onClick={async()=>{if(window.confirm('Nạp bản nháp đã lưu từ phiên bản cũ trên trình duyệt này?')){try{const raw=JSON.parse(localStorage.getItem('ngoc-dong-cms-v1')!);await importContent(raw.draft);}catch(e){setError((e as Error).message);}}}}>Khôi phục bản nháp trên trình duyệt cũ</button>}</section>}

 </fieldset>}
 <div className="cms-bottom"><button onClick={backup} disabled={!ready}>Tải bản sao lưu</button><span>{publishedAt?`Xuất bản gần nhất: ${new Date(publishedAt).toLocaleString('vi-VN')}`:'Chưa có thay đổi được xuất bản'}</span><a href="/" target="_blank" rel="noreferrer">Xem trang chính ↗</a></div></div></div>
 <dialog className="cms-preview-dialog" ref={dialog} onCancel={()=>setPreview(false)} onClose={()=>{setPreview(false);previewTrigger.current?.focus();}}><div className="cms-preview-toolbar"><div><strong>Xem trước bản nháp</strong><small>Kiểm tra bản nháp trước khi cập nhật website cho khách.</small></div><div className="cms-preview-actions"><button aria-label="Xem trên máy tính" aria-pressed={!mobile} onClick={()=>setMobile(false)}><Monitor size={20}/></button><button aria-label="Xem trên điện thoại" aria-pressed={mobile} onClick={()=>setMobile(true)}><Smartphone size={20}/></button><button className="primary" disabled={busy} onClick={publish}><Upload size={17}/>Xuất bản</button><button aria-label="Đóng xem trước" onClick={()=>setPreview(false)}><X size={20}/></button></div></div>{error&&<p role="alert" className="cms-error">{error}</p>}<div className="cms-preview-stage">{preview&&<iframe key={previewKey} title="Bản xem trước website" src={previewPath} style={{width:mobile?'390px':'100%'}}/>}</div></dialog>
 </div>;
}
