'use client';
import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform, useMotionValueEvent } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Menu, X, Phone, MapPin, Leaf, Coffee, Waves, Utensils, Heart, Footprints, Compass, BedDouble, ChevronLeft, ChevronRight, Pause, Play, Quote } from 'lucide-react';
import { address, gallery, mapQuery, media, rooms, scenes } from '../lib/content';
const experiences=[
 {icon:Leaf,title:'Nghỉ giữa thiên nhiên',text:'Dành chỗ cho những buổi sáng thảnh thơi.'},
 {icon:Compass,title:'Đồi chè Long Cốc',text:'Hẹn bình minh trên những đồi chè xanh.'},
 {icon:Waves,title:'Một chiều bên hồ bơi',text:'Thêm một khoảng thư giãn vào ngày nghỉ.'},
 {icon:Coffee,title:'Cà phê & ngắm cảnh',text:'Một tách cà phê. Một câu chuyện chưa hết.'},
 {icon:Utensils,title:'Một bữa cơm quê',text:'Tìm lại niềm vui từ bữa cơm quây quần.'},
 {icon:Footprints,title:'Ngâm chân thảo dược',text:'Gợi ý thư giãn sau một ngày dạo bước.'},
 {icon:Heart,title:'Chỉ hai chúng mình',text:'Thời gian dành riêng cho người bên cạnh.'},
 {icon:MapPin,title:'Cuối tuần rời Hà Nội',text:'Đổi nhịp cuối tuần bằng một chuyến về Làng.'},
];
function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){ const reduced=useReducedMotion(); return <motion.div className={className} initial={false} whileInView={reduced?{}:{opacity:[.6,1],y:[20,0]}} viewport={{once:true,amount:.15}} transition={{duration:.7}}>{children}</motion.div>; }
function Story(){
 const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const [active,setActive]=useState(0);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});
 useMotionValueEvent(scrollYProgress,'change',v=>{if(!reduced)setActive(Math.min(5,Math.floor(v*6)));});
 const current=scenes[active];
 return <section id="story" ref={ref} className={`story ${reduced?'reduced':''}`} aria-label="Một ngày ở Làng qua sáu khoảnh khắc"><div className="story-stage"><AnimatePresence mode="sync"><motion.div key={current.id} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.8}} className={`story-image ${current.tone||''}`}><img src={current.image} alt={current.title} style={{objectPosition:current.position}} loading="lazy"/>{current.video&&!reduced&&<video src={current.video} autoPlay muted loop playsInline poster={current.image}/>}</motion.div></AnimatePresence><div className="story-overlay"/><div className="story-top"><span className="eyebrow">MỘT NGÀY, MỘT NHỊP SỐNG KHÁC</span><span>0{active+1} / 06</span></div><div className="story-copy"><p className="eyebrow">{current.time}</p><h2>{current.title}</h2><p>{current.text}</p></div><div className="story-nav">{scenes.map((s,i)=><button key={s.id} aria-label={`Xem cảnh ${i+1}: ${s.title}`} aria-current={i===active?'step':undefined} onClick={()=>{if(reduced){setActive(i);return;}if(ref.current)window.scrollTo({top:ref.current.offsetTop+(ref.current.offsetHeight-window.innerHeight)*(i+.15)/6,behavior:'smooth'});}}><span className={i<=active?'filled':''}/><small>{s.time.split(' · ')[1]}</small></button>)}</div><span className="story-caption">{current.illustrative?'Khung cảnh minh họa cho hành trình':'Đồi chè Long Cốc · Ảnh Nguyen Trong Quyet'}</span></div></section>;
}
export default function Home(){
 const reduced=useReducedMotion();const [menu,setMenu]=useState(false);const [selected,setSelected]=useState<number|null>(null);const [map,setMap]=useState(false);const [videoPaused,setVideoPaused]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const galleryDialog=useRef<HTMLDialogElement>(null);const closeButton=useRef<HTMLButtonElement>(null);
 const heroRef=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:heroRef,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],['0%','20%']);
 useEffect(()=>{if(selected!==null){galleryDialog.current?.showModal();document.body.style.overflow='hidden';}else{galleryDialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[selected]);
 useEffect(()=>{if(!menu)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[menu]);
 const links=[['Câu chuyện Làng','#about'],['Trải nghiệm','#experiences'],['Ở tại Làng','#rooms'],['Tìm đường','#location']];
 return <main><a href="#about" className="skip-link">Đến nội dung chính</a><header className="nav"><a className="brand" href="#" aria-label="Làng Sinh Thái Ngọc Đồng, trang chủ"><span className="brand-icon">NĐ</span><span>NGỌC ĐỒNG<small>LÀNG SINH THÁI</small></span></a><nav aria-label="Điều hướng chính">{links.map(([title,href])=><a key={href} href={href}>{title}</a>)}</nav><div className="nav-actions"><a className="button light small" href="#booking">Đặt phòng <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={menu?'Đóng menu':'Mở menu'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Điều hướng trên điện thoại">{links.map(([title,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{title}<ArrowUpRight size={18}/></a>)}<a href="tel:0965163291">0965 163 291 <Phone size={18}/></a></nav>}</header>
 <section className="hero" ref={heroRef}><motion.div className="hero-media" style={{y:reduced?0:y}}><img className="hero-img" src={media.hero.image} alt="Sương sớm trên những đồi chè xanh Long Cốc" fetchPriority="high"/>{media.hero.video&&!reduced&&<video ref={videoRef} className="hero-img" autoPlay muted loop playsInline poster={media.hero.image}>{media.hero.webm&&<source src={media.hero.webm} type="video/webm"/>}<source src={media.hero.video} type="video/mp4"/></video>}</motion.div><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">THANH SƠN, PHÚ THỌ · VIỆT NAM</p><h1>Về Làng,<br/>chạm vào một<br/><em>nhịp sống khác.</em></h1><p>Nghỉ dưỡng giữa thiên nhiên Thanh Sơn – gần đồi chè Long Cốc,<br className="desktop"/> nơi dành cho những ngày muốn sống chậm lại.</p><div className="hero-actions"><a className="button light" href="#booking">Đặt phòng tại Làng <ArrowUpRight size={18}/></a><a className="text-link" href="#about">Khám phá Làng <ArrowDown size={16}/></a></div></div><div className="hero-bottom"><span>RỜI PHỐ MỘT CHÚT. GẦN NHAU HƠN.</span><a href="#about">CUỘN ĐỂ CẢM NHẬN <ArrowDown size={14}/></a>{media.hero.video&&!reduced?<button className="video-toggle" aria-label={videoPaused?'Phát video nền':'Tạm dừng video nền'} onClick={()=>{if(videoPaused)videoRef.current?.play();else videoRef.current?.pause();setVideoPaused(!videoPaused);}}>{videoPaused?<Play size={15}/>:<Pause size={15}/>}</button>:<span>LONG CỐC · BÌNH MINH</span>}</div></section>
 <section id="about" className="section about"><Reveal><p className="eyebrow green">MỘT NƠI ĐỂ TRỞ VỀ</p><h2>Không cần đi thật xa.<br/>Chỉ cần một khoảng <em>xanh.</em></h2><p className="intro">Ở Ngọc Đồng, hãy dành thời gian cho một tách trà, một cuộc trò chuyện dài và những buổi sáng không vội. Một khoảng dừng giữa thiên nhiên Thanh Sơn, Phú Thọ.</p><div className="about-sign"><Leaf size={23} strokeWidth={1}/><span>Mộc mạc trong từng điều nhỏ.</span></div></Reveal><div className="about-pictures"><figure className="about-landscape"><img src={media.hero.image} alt="Những đồi chè nối nhau trong sương tại Long Cốc" loading="lazy"/><figcaption>01 — MÀU XANH CỦA MIỀN TRUNG DU</figcaption></figure><figure className="about-tea"><img src={media.tea} alt="Ấm trà gốm xanh, ảnh minh họa" loading="lazy"/><figcaption>02 — MỘT CHÚT THẢNH THƠI · ẢNH MINH HỌA</figcaption></figure><p className="vertical-note">NATURE. SIMPLICITY. CONNECTION.</p></div></section>
 <section id="experiences" className="section experiences"><Reveal className="section-heading"><div><p className="eyebrow green">NHỮNG ĐIỀU NHỎ, NIỀM VUI LỚN</p><h2>Ở Làng, mình làm gì?</h2></div><p>Không cần lấp đầy lịch trình.<br/>Cứ chọn điều khiến mình thấy dễ chịu.</p></Reveal><div className="experience-grid">{experiences.map(({icon:Icon,title,text},i)=><Reveal className="experience" key={title}><div className="experience-top"><Icon size={28} strokeWidth={1.2}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></Reveal>)}</div><p className="fine-print">Gợi ý cho chuyến đi. Vui lòng liên hệ Làng để xác nhận dịch vụ và lịch trải nghiệm tại thời điểm lưu trú.</p></section>
 <section id="rooms" className="section rooms"><Reveal className="section-heading"><div><p className="eyebrow green">Ở LẠI THÊM MỘT CHÚT</p><h2>Một nơi nghỉ.<br/>Nhiều điều để nhớ.</h2></div><div><p>Chọn không gian cho chuyến đi của mình.</p><a className="dark-link" href="#booking">Hỏi Làng về phòng trống <ArrowUpRight size={18}/></a></div></Reveal><div className="room-grid">{rooms.map((room,i)=><Reveal className="room" key={room.name}><div className={`room-image room-${i}`}><img src={room.image} alt={`${room.name}, ảnh phòng minh họa`} loading="lazy"/><span className="image-label">ẢNH MINH HỌA</span></div><div className="room-content"><p className="eyebrow green">{room.tag}</p><h3>{room.name}</h3><p>{room.text}</p><div className="room-capacity"><BedDouble size={18}/>{room.capacity}</div><div className="room-bottom"><strong>{room.price}</strong><a href="#booking" aria-label={`Hỏi phòng: ${room.name}`}>Hỏi phòng <ArrowUpRight size={18}/></a></div></div></Reveal>)}</div><p className="fine-print">Không gian gợi ý trong bản giới thiệu. Danh mục phòng, sức chứa và giá chính thức đang được cập nhật.</p></section>
 <Story/>
 <section id="long-coc" className="section long-coc"><div className="long-coc-image"><img src={media.hero.image} alt="Đồi chè Long Cốc, Phú Thọ trong ánh nắng sớm" loading="lazy"/><span className="photo-credit">LONG CỐC, PHÚ THỌ</span></div><Reveal className="long-coc-copy"><p className="eyebrow green">MỘT ĐIỂM HẸN VỚI BÌNH MINH</p><h2>Long Cốc.<br/>Xanh đến tận <br/><em>chân trời.</em></h2><p>Những đồi chè nối nhau, lớp sương mỏng và ánh sáng đầu ngày. Long Cốc là một gợi ý để dành trọn buổi sáng cho thiên nhiên trong chuyến nghỉ dưỡng Phú Thọ.</p><p>Nếu anh chị đang tìm homestay gần đồi chè Long Cốc hoặc một nơi nghỉ dưỡng Thanh Sơn, hãy liên hệ Làng Ngọc Đồng để được tư vấn phòng và lộ trình phù hợp.</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('Đồi chè Long Cốc Phú Thọ')}`} target="_blank" rel="noreferrer" className="dark-link">Xem đồi chè Long Cốc trên bản đồ <ArrowUpRight size={18}/></a></Reveal></section>
 <section id="couples" className="couples"><img src={media.room} alt="Không gian gỗ ấm áp, ảnh minh họa cho kỳ nghỉ hai người" loading="lazy"/><div className="couples-overlay"/><Reveal className="couples-copy"><Heart size={28} strokeWidth={1}/><p className="eyebrow">MỘT CHUYẾN ĐI CHO HAI</p><h2>Ít thông báo hơn.<br/><em>Nhiều chuyện để kể hơn.</em></h2><p>Một buổi sáng cùng uống trà. Một chiều chẳng cần đi đâu.<br/>Đôi khi, điều mình cần chỉ là thời gian bên nhau.</p><a className="button light" href="#booking">Hẹn một cuối tuần của hai mình <ArrowUpRight size={18}/></a></Reveal><span className="couples-caption">KHÔNG GIAN MINH HỌA</span></section>
 <section id="gallery" className="section gallery"><Reveal className="section-heading"><div><p className="eyebrow green">GIỮ LẠI MỘT KHOẢNH KHẮC</p><h2>Chút bình yên, mang về.</h2></div><p>Những sắc màu gợi cảm hứng cho chuyến đi.</p></Reveal><div className="gallery-grid">{gallery.map((item,i)=><button key={item.src} className={`gallery-item gallery-${i}`} onClick={()=>setSelected(i)} aria-label={`Mở ảnh: ${item.caption}`}><img src={item.src} alt={item.alt} loading="lazy"/><span>{item.caption}<ArrowUpRight size={18}/></span>{item.illustrative&&<small>ẢNH MINH HỌA</small>}</button>)}</div></section>
 <section id="reviews" className="section reviews"><Quote size={38} strokeWidth={1}/><p className="eyebrow green">CHUYỆN SAU MỖI LẦN GHÉ</p><h2>Mỗi chuyến về Làng,<br/>một câu chuyện riêng.</h2><p>Những cảm nhận đầu tiên đang chờ được chia sẻ.<br/>Làng sẽ cập nhật đánh giá đã được xác thực tại đây.</p><span className="review-rule"/><p className="review-note">Anh chị đã ghé Làng? Gửi lời nhắn qua <a href="https://zalo.me/0965163291" target="_blank" rel="noreferrer">Zalo của Làng <ArrowUpRight size={14}/></a>.</p></section>
 <section id="location" className="section location"><Reveal className="location-copy"><p className="eyebrow green">ĐƯỜNG VỀ LÀNG</p><h2>Hẹn gặp nhau<br/>ở <em>Ngọc Đồng.</em></h2><p className="address"><MapPin size={22}/><span>{address}</span></p><p>Trước khi khởi hành, anh chị gọi Làng để được hướng dẫn lối vào và xác nhận điểm đón phù hợp.</p><a className="dark-link" href={`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank" rel="noreferrer">Mở chỉ đường Google Maps <ArrowUpRight size={18}/></a><a className="location-phone" href="tel:0965163291"><Phone size={18}/>0965 163 291</a></Reveal><div className="map-panel">{map?<iframe title="Bản đồ tìm kiếm Ngọc Đồng, Thục Luyện, Thanh Sơn, Phú Thọ" src={`https://maps.google.com/maps?q=${mapQuery}&z=13&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/>:<div className="map-placeholder"><MapPin size={42} strokeWidth={1}/><span className="eyebrow">NGỌC ĐỒNG · PHÚ THỌ</span><h3>Một chuyến về miền xanh.</h3><button className="button forest" onClick={()=>setMap(true)}>Hiển thị bản đồ <ArrowUpRight size={18}/></button><p>Bản đồ tìm theo địa chỉ, chưa xác minh ghim của Làng.</p></div>}</div></section>
 <section id="booking" className="section booking"><Reveal><p className="eyebrow">DÀNH CHO MỘT NGÀY KHÔNG VỘI</p><h2>Làng vẫn ở đây.<br/><em>Chờ một ngày anh chị ghé.</em></h2><p>Cho Làng biết ngày dự kiến, số khách và không gian mong muốn.<br/>Mình cùng tìm một kỳ nghỉ vừa vặn.</p><div className="booking-actions"><a className="button light" href="tel:0965163291"><Phone size={18}/>Gọi đặt phòng · 0965 163 291</a><a className="button outline" href="https://zalo.me/0965163291" target="_blank" rel="noreferrer">Nhắn Zalo cho Làng <ArrowUpRight size={18}/></a></div><p className="booking-note">Phòng và mức giá được xác nhận trực tiếp cùng Làng.</p></Reveal></section>
 <footer><div className="footer-main"><div><a className="brand" href="#"><span className="brand-icon">NĐ</span><span>NGỌC ĐỒNG<small>LÀNG SINH THÁI</small></span></a><p>Về Làng, chạm vào một nhịp sống khác.</p></div><div><p className="eyebrow">KHÁM PHÁ</p><a href="#rooms">Ở tại Làng</a><a href="#experiences">Trải nghiệm</a><a href="#long-coc">Đồi chè Long Cốc</a></div><div><p className="eyebrow">KẾT NỐI VỚI LÀNG</p><a href="tel:0965163291">0965 163 291</a><p>{address}</p><a href="https://zalo.me/0965163291" target="_blank" rel="noreferrer">Zalo <ArrowUpRight size={14}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Làng Sinh Thái Ngọc Đồng</span><span>Ảnh phòng, hồ bơi và trà là ảnh minh họa.</span><a href="#">Về đầu trang ↑</a></div></footer>
 <dialog ref={galleryDialog} className="lightbox" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}} onKeyDown={e=>{if(e.key==='ArrowRight')setSelected(v=>v===null?null:(v+1)%gallery.length);if(e.key==='ArrowLeft')setSelected(v=>v===null?null:(v+gallery.length-1)%gallery.length);}}>{selected!==null&&<><button ref={closeButton} className="lightbox-close" autoFocus aria-label="Đóng ảnh" onClick={()=>setSelected(null)}><X/></button><button className="lightbox-prev" aria-label="Ảnh trước" onClick={()=>setSelected((selected+gallery.length-1)%gallery.length)}><ChevronLeft/></button><figure><img src={gallery[selected].src} alt={gallery[selected].alt}/><figcaption>{gallery[selected].caption}{gallery[selected].illustrative?' · Ảnh minh họa':''}<span>{selected+1} / {gallery.length}</span></figcaption></figure><button className="lightbox-next" aria-label="Ảnh tiếp theo" onClick={()=>setSelected((selected+1)%gallery.length)}><ChevronRight/></button></>}</dialog>
 </main>;
}
