'use client';
import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform, useMotionValueEvent } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Menu, X, Phone, MessageCircle, MapPin, Leaf, Coffee, Waves, Utensils, Heart, Footprints, Compass, BedDouble, ChevronLeft, ChevronRight, Pause, Play, Quote } from 'lucide-react';
import { useSiteContent, OrderedMain } from '../lib/cms-client';
import type { SiteContent } from '../lib/cms';
const experienceDefaults=[
 {icon:Leaf,title:'Nghỉ giữa thiên nhiên',text:'Dành chỗ cho những buổi sáng thảnh thơi.'},
 {icon:Compass,title:'Đồi chè Long Cốc',text:'Hẹn bình minh trên những đồi chè xanh.'},
 {icon:Waves,title:'Một chiều bên hồ bơi',text:'Thêm một khoảng thư giãn vào ngày nghỉ.'},
 {icon:Coffee,title:'Cà phê & ngắm cảnh',text:'Một tách cà phê. Một câu chuyện chưa hết.'},
 {icon:Utensils,title:'Một bữa cơm quê',text:'Tìm lại niềm vui từ bữa cơm quây quần.'},
 {icon:Footprints,title:'Ngâm chân thảo dược',text:'Gợi ý thư giãn sau một ngày dạo bước.'},
 {icon:Heart,title:'Chỉ hai chúng mình',text:'Thời gian dành riêng cho người bên cạnh.'},
 {icon:MapPin,title:'Cuối tuần rời Hà Nội',text:'Đổi nhịp cuối tuần bằng một chuyến về Làng.'},
];
function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){ const reduced=useReducedMotion(); return <motion.div className={className} initial={false} whileInView={reduced?{}:{opacity:[.6,1],y:[20,0]}} viewport={{once:true,amount:.15}} transition={{duration:.7}}>{children}</motion.div>; }
function Story({scenes,copy}:{scenes:SiteContent["scenes"];copy:SiteContent["copy"]}){
 const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const [active,setActive]=useState(0);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});
 useMotionValueEvent(scrollYProgress,'change',v=>{if(!reduced)setActive(Math.min(5,Math.floor(v*6)));});
 const current=scenes[active];
 return <section id="story" ref={ref} className={`story ${reduced?'reduced':''}`} aria-label="Một ngày ở Làng qua sáu khoảnh khắc"><div className="story-stage"><AnimatePresence mode="sync"><motion.div key={current.id} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.8}} className={`story-image ${current.tone||''}`}><img src={current.image} alt={current.alt} style={{objectPosition:current.position}} loading="lazy"/>{current.video&&!reduced&&<video src={current.video} autoPlay muted loop playsInline poster={current.image}/>}</motion.div></AnimatePresence><div className="story-overlay"/><div className="story-top"><span className="eyebrow">{copy.story_1}</span><span>0{active+1}{copy.story_2}</span></div><div className="story-copy"><p className="eyebrow">{current.time}</p><h2>{current.title}</h2><p>{current.text}</p></div><div className="story-nav">{scenes.map((s,i)=><button key={s.id} aria-label={`Xem cảnh ${i+1}: ${s.title}`} aria-current={i===active?'step':undefined} onClick={()=>{if(reduced){setActive(i);return;}if(ref.current)window.scrollTo({top:ref.current.offsetTop+(ref.current.offsetHeight-window.innerHeight)*(i+.15)/6,behavior:'smooth'});}}><span className={i<=active?'filled':''}/><small>{s.navLabel}</small></button>)}</div><span className="story-caption">{current.credit}</span></div></section>;
}
export default function Home({preview=false,initialContent}:{preview?:boolean;initialContent?:SiteContent}){
 const {content,error}=useSiteContent(preview,initialContent);const {copy,media,rooms,scenes,gallery,address}=content;const mapQuery=encodeURIComponent(address);const experiences=content.experiences.map((item,i)=>({...item,icon:experienceDefaults[i%experienceDefaults.length].icon}));
 const reduced=useReducedMotion();const [menu,setMenu]=useState(false);const [bookingMenu,setBookingMenu]=useState(false);const bookingMenuRef=useRef<HTMLDivElement>(null);const [selected,setSelected]=useState<number|null>(null);const [map,setMap]=useState(false);const [videoPaused,setVideoPaused]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const galleryDialog=useRef<HTMLDialogElement>(null);const closeButton=useRef<HTMLButtonElement>(null);
 const heroRef=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:heroRef,offset:['start start','end start']});const y=useTransform(scrollYProgress,[0,1],['0%','20%']);
 useEffect(()=>{if(selected!==null){galleryDialog.current?.showModal();document.body.style.overflow='hidden';}else{galleryDialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[selected]);
 useEffect(()=>{if(!menu)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[menu]);
 useEffect(()=>{if(!bookingMenu)return;const close=(e:PointerEvent)=>{if(!bookingMenuRef.current?.contains(e.target as Node))setBookingMenu(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setBookingMenu(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[bookingMenu]);
 const links=content.navigation.map(n=>[n.label,n.href]);
 const whatsapp=content.contact.whatsapp||`https://wa.me/${content.contact.phone.replace(/\D/g,'').replace(/^0/,'84')}?text=${encodeURIComponent('Chào Làng Ngọc Đồng, tôi muốn hỏi thông tin và đặt phòng.')}`;
 return <OrderedMain order={content.order}>{error&&<p className="cms-load-error" role="alert">{error}</p>}<a href="#about" className="skip-link">{copy.general_1}</a><header className="nav"><a className="brand" href="#" aria-label="Làng Sinh Thái Ngọc Đồng, trang chủ"><span className="brand-icon">{copy.header_1}</span><span>{copy.header_2}<small>{copy.header_3}</small></span></a><nav aria-label="Điều hướng chính">{links.map(([title,href],i)=><a key={i} href={href}>{title}</a>)}</nav><div className="nav-actions"><div className="booking-menu" ref={bookingMenuRef}><button type="button" className="button light small booking-menu-trigger" aria-haspopup="true" aria-expanded={bookingMenu} aria-controls="booking-contact-options" onClick={()=>{setMenu(false);setBookingMenu(v=>!v);}}>{copy.header_4}<ArrowUpRight size={16}/></button>{bookingMenu&&<div id="booking-contact-options" className="booking-contact-options" role="group" aria-label="Chọn kênh liên hệ đặt phòng"><a href={content.contact.zalo} target="_blank" rel="noopener noreferrer" onClick={()=>setBookingMenu(false)}><span className="contact-icon zalo-icon" aria-hidden="true">Z</span><span>Zalo<small>Nhắn tin đặt phòng</small></span><ArrowUpRight size={16}/></a><a href={whatsapp} target="_blank" rel="noopener noreferrer" onClick={()=>setBookingMenu(false)}><span className="contact-icon whatsapp-icon" aria-hidden="true"><MessageCircle size={24}/><Phone size={12}/></span><span>WhatsApp<small>Nhắn tin đặt phòng</small></span><ArrowUpRight size={16}/></a></div>}</div><button className="menu-toggle" aria-label={menu?'Đóng menu':'Mở menu'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>{setBookingMenu(false);setMenu(!menu);}}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Điều hướng trên điện thoại">{links.map(([title,href],i)=><a key={i} href={href} onClick={()=>setMenu(false)}>{title}<ArrowUpRight size={18}/></a>)}<a href={`tel:${content.contact.phone.replace(/[^+\d]/g,'')}`}>{content.contact.phone}<Phone size={18}/></a></nav>}</header>
 <section className="hero" ref={heroRef}><motion.div className="hero-media" style={{y:reduced?0:y}}><img className="hero-img" src={media.hero.image} alt={content.heroAlt} fetchPriority="high"/>{media.hero.video&&!reduced&&<video ref={videoRef} className="hero-img" autoPlay muted loop playsInline poster={media.hero.image}>{media.hero.webm&&<source src={media.hero.webm} type="video/webm"/>}<source src={media.hero.video} type="video/mp4"/></video>}</motion.div><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">{copy.hero_1}</p><h1>{copy.hero_2}<br/>{copy.hero_3}<br/><em>{copy.hero_4}</em></h1><p>{copy.hero_5}<br className="desktop"/>{copy.hero_6}</p><div className="hero-actions"><a className="button light" href={content.links.heroBooking}>{copy.hero_7}<ArrowUpRight size={18}/></a><a className="text-link" href={content.links.heroExplore}>{copy.hero_8}<ArrowDown size={16}/></a></div></div><div className="hero-bottom"><span>{copy.hero_9}</span><a href={content.links.heroScroll}>{copy.hero_10}<ArrowDown size={14}/></a>{media.hero.video&&!reduced?<button className="video-toggle" aria-label={videoPaused?'Phát video nền':'Tạm dừng video nền'} onClick={()=>{if(videoPaused)videoRef.current?.play();else videoRef.current?.pause();setVideoPaused(!videoPaused);}}>{videoPaused?<Play size={15}/>:<Pause size={15}/>}</button>:<span>{copy.hero_11}</span>}</div></section>
 <section id="about" className="section about"><Reveal><p className="eyebrow green">{copy.about_1}</p><h2>{copy.about_2}<br/>{copy.about_3}<em>{copy.about_4}</em></h2><p className="intro">{copy.about_5}</p><div className="about-sign"><Leaf size={23} strokeWidth={1}/><span>{copy.about_6}</span></div></Reveal><div className="about-pictures"><figure className="about-landscape"><img src={content.images.aboutLandscape.image} alt={content.images.aboutLandscape.alt} loading="lazy"/><figcaption>{copy.about_7}</figcaption></figure><figure className="about-tea"><img src={content.images.aboutTea.image} alt={content.images.aboutTea.alt} loading="lazy"/><figcaption>{copy.about_8}</figcaption></figure><p className="vertical-note">{copy.about_9}</p></div></section>
 <section id="experiences" className="section experiences"><Reveal className="section-heading"><div><p className="eyebrow green">{copy.experiences_1}</p><h2>{copy.experiences_2}</h2></div><p>{copy.experiences_3}<br/>{copy.experiences_4}</p></Reveal><div className="experience-grid">{experiences.map(({icon:Icon,title,text},i)=><Reveal className="experience" key={i}><div className="experience-top"><Icon size={28} strokeWidth={1.2}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></Reveal>)}</div><p className="fine-print">{copy.experiences_5}</p></section>
 <section id="rooms" className="section rooms"><Reveal className="section-heading"><div><p className="eyebrow green">{copy.rooms_1}</p><h2>{copy.rooms_2}<br/>{copy.rooms_3}</h2></div><div><p>{copy.rooms_4}</p><a className="dark-link" href={content.links.roomsEnquiry}>{copy.rooms_5}<ArrowUpRight size={18}/></a></div></Reveal><div className="room-grid">{rooms.map((room,i)=><Reveal className="room" key={i}><div className={`room-image room-${i}`}><img src={room.image} alt={room.alt} loading="lazy"/>{room.illustrative&&<span className="image-label">{copy.rooms_6}</span>}</div><div className="room-content"><p className="eyebrow green">{room.tag}</p><h3>{room.name}</h3><p>{room.text}</p>{room.amenities&&<p className="room-amenities">{room.amenities}</p>}<div className="room-capacity"><BedDouble size={18}/>{room.capacity}</div><div className="room-bottom"><strong>{room.price}</strong><a href={room.ctaHref} aria-label={`${room.ctaLabel}: ${room.name}`}>{room.ctaLabel}<ArrowUpRight size={18}/></a></div></div></Reveal>)}</div><p className="fine-print">{copy.rooms_8}</p></section>
 <Story scenes={scenes} copy={copy}/>
 <section id="long-coc" className="section long-coc"><div className="long-coc-image"><img src={content.images.longCoc.image} alt={content.images.longCoc.alt} loading="lazy"/><span className="photo-credit">{copy["long-coc_1"]}</span></div><Reveal className="long-coc-copy"><p className="eyebrow green">{copy["long-coc_2"]}</p><h2>{copy["long-coc_3"]}<br/>{copy["long-coc_4"]}<br/><em>{copy["long-coc_5"]}</em></h2><p>{copy["long-coc_6"]}</p><p>{copy["long-coc_7"]}</p><a href={content.links.longCocMap} target="_blank" rel="noreferrer" className="dark-link">{copy["long-coc_8"]}<ArrowUpRight size={18}/></a></Reveal></section>
 <section id="couples" className="couples"><img src={content.images.couples.image} alt={content.images.couples.alt} loading="lazy"/><div className="couples-overlay"/><Reveal className="couples-copy"><Heart size={28} strokeWidth={1}/><p className="eyebrow">{copy.couples_1}</p><h2>{copy.couples_2}<br/><em>{copy.couples_3}</em></h2><p>{copy.couples_4}<br/>{copy.couples_5}</p><a className="button light" href={content.links.couplesBooking}>{copy.couples_6}<ArrowUpRight size={18}/></a></Reveal><span className="couples-caption">{copy.couples_7}</span></section>
 <section id="gallery" className="section gallery"><Reveal className="section-heading"><div><p className="eyebrow green">{copy.gallery_1}</p><h2>{copy.gallery_2}</h2></div><p>{copy.gallery_3}</p></Reveal><div className="gallery-grid">{gallery.map((item,i)=><button key={i} className={`gallery-item gallery-${i}`} onClick={()=>setSelected(i)} aria-label={`Mở ảnh: ${item.caption}`}><img src={item.src} alt={item.alt} loading="lazy"/><span>{item.caption}<ArrowUpRight size={18}/></span>{item.illustrative&&<small>{copy.gallery_4}</small>}</button>)}</div></section>
 <section id="reviews" className="section reviews"><Quote size={38} strokeWidth={1}/><p className="eyebrow green">{copy.reviews_1}</p><h2>{copy.reviews_2}<br/>{copy.reviews_3}</h2><p>{copy.reviews_4}<br/>{copy.reviews_5}</p><span className="review-rule"/><p className="review-note">{copy.reviews_6}<a href={content.contact.zalo} target="_blank" rel="noreferrer">{copy.reviews_7}<ArrowUpRight size={14}/></a>{copy.reviews_8}</p></section>
 <section id="location" className="section location"><Reveal className="location-copy"><p className="eyebrow green">{copy.location_1}</p><h2>{copy.location_2}<br/>{copy.location_3}<em>{copy.location_4}</em></h2><p className="address"><MapPin size={22}/><span>{address}</span></p><p>{copy.location_5}</p><a className="dark-link" href={content.contact.googleMaps||`https://www.google.com/maps/search/?api=1&query=${mapQuery}`} target="_blank" rel="noreferrer">{copy.location_6}<ArrowUpRight size={18}/></a><a className="location-phone" href={`tel:${content.contact.phone.replace(/[^+\d]/g,'')}`}><Phone size={18}/>{content.contact.phone}</a></Reveal><div className="map-panel">{map?<iframe title="Bản đồ tìm kiếm Ngọc Đồng, Thục Luyện, Thanh Sơn, Phú Thọ" src={`https://maps.google.com/maps?q=${mapQuery}&z=13&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/>:<div className="map-placeholder"><MapPin size={42} strokeWidth={1}/><span className="eyebrow">{copy.location_8}</span><h3>{copy.location_9}</h3><button className="button forest" onClick={()=>setMap(true)}>{copy.location_10}<ArrowUpRight size={18}/></button><p>{copy.location_11}</p></div>}</div></section>
 <section id="booking" className="section booking"><Reveal><p className="eyebrow">{copy.booking_1}</p><h2>{copy.booking_2}<br/><em>{copy.booking_3}</em></h2><p>{copy.booking_4}<br/>{copy.booking_5}</p><div className="booking-actions"><a className="button light" href={`tel:${content.contact.phone.replace(/[^+\d]/g,'')}`}><Phone size={18}/>{copy.booking_6} · {content.contact.phone}</a><a className="button outline" href={content.contact.zalo} target="_blank" rel="noreferrer">{copy.booking_7}<ArrowUpRight size={18}/></a></div><div className="contact-extra">{(['facebook','booking','whatsapp'] as const).filter(k=>content.contact[k]).map(k=><a key={k} href={content.contact[k]} target="_blank" rel="noreferrer">{{facebook:'Facebook',booking:'Booking',whatsapp:'WhatsApp'}[k]} ↗</a>)}</div><p className="booking-note">{copy.booking_8}</p></Reveal></section>
 <div className="blog-access"><a href={preview?"/blog/?preview=1":"/blog/"}>Bài viết · Chuyện ở Làng ↗</a></div><footer><div className="footer-main"><div><a className="brand" href="#"><span className="brand-icon">{copy.footer_1}</span><span>{copy.footer_2}<small>{copy.footer_3}</small></span></a><p>{copy.footer_4}</p></div><div><p className="eyebrow">{copy.footer_5}</p><a href={content.links.footerRooms}>{copy.footer_6}</a><a href={content.links.footerExperiences}>{copy.footer_7}</a><a href={content.links.footerLongCoc}>{copy.footer_8}</a></div><div><p className="eyebrow">{copy.footer_9}</p><a href={`tel:${content.contact.phone.replace(/[^+\d]/g,'')}`}>{content.contact.phone}</a><p>{address}</p><a href={content.contact.zalo} target="_blank" rel="noreferrer">{copy.footer_11}<ArrowUpRight size={14}/></a></div></div><div className="footer-bottom"><span>{copy.footer_12}{new Date().getFullYear()}{copy.footer_13}</span><span>{copy.footer_14}</span><a href="#">{copy.footer_15}</a></div></footer>
 <dialog ref={galleryDialog} className="lightbox" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}} onKeyDown={e=>{if(e.key==='ArrowRight')setSelected(v=>v===null?null:(v+1)%gallery.length);if(e.key==='ArrowLeft')setSelected(v=>v===null?null:(v+gallery.length-1)%gallery.length);}}>{selected!==null&&<><button ref={closeButton} className="lightbox-close" autoFocus aria-label="Đóng ảnh" onClick={()=>setSelected(null)}><X/></button><button className="lightbox-prev" aria-label="Ảnh trước" onClick={()=>setSelected((selected+gallery.length-1)%gallery.length)}><ChevronLeft/></button><figure><img src={gallery[selected].src} alt={gallery[selected].alt}/><figcaption>{gallery[selected].caption}{gallery[selected].illustrative?' · '+copy.gallery_4:''}<span>{selected+1}{copy.general_2}{gallery.length}</span></figcaption></figure><button className="lightbox-next" aria-label="Ảnh tiếp theo" onClick={()=>setSelected((selected+1)%gallery.length)}><ChevronRight/></button></>}</dialog>
 </OrderedMain>;
}
