import {migrateContent,validateContent,type Snapshot,type SiteContent,type ContentRepository,type AdminAuth,type AssetStorage} from './cms';
let revision:number|undefined;
export async function api(path:string,init:RequestInit={}){const response=await fetch(path,{...init,cache:'no-store',credentials:'same-origin'});const result=await response.json().catch(()=>({error:'Máy chủ chưa phản hồi. Vui lòng thử lại.'}));if(!response.ok)throw new Error(result.error||'Không thực hiện được thao tác.');return result;}
export const contentRepository:ContentRepository={async load(){const s=await api('/api/admin/content') as Snapshot;revision=s.revision;return {...s,draft:migrateContent(s.draft),published:migrateContent(s.published)};},async saveDraft(content){validateContent(content);const s=await api('/api/admin/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,revision,action:'draft'})});revision=s.revision;window.dispatchEvent(new Event('cms-change'));},async publish(content){validateContent(content);const s=await api('/api/admin/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,revision,action:'publish'})});revision=s.revision;window.dispatchEvent(new Event('cms-change'));}};
export const adminAuth:AdminAuth={async getSession(){await api('/api/admin/session');return {mode:'server',label:'Quản trị Ngọc Đồng'};}};
export async function loadPublicContent(preview=false):Promise<SiteContent>{const s=await api(preview?'/api/admin/content':'/api/content');return migrateContent(preview?s.draft:s.content);}
export const assetStorage:AssetStorage={async upload(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Vui lòng chọn ảnh JPG, PNG hoặc WebP.');
 if(file.size>10*1024*1024)throw new Error('Ảnh quá lớn. Vui lòng chọn ảnh dưới 10 MB.');
 const bitmap=await createImageBitmap(file).catch(()=>{throw new Error('Không đọc được ảnh. Hãy chọn file ảnh khác.');});
 try{const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Trình duyệt chưa hỗ trợ xử lý ảnh.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Không xử lý được ảnh.')),'image/jpeg',.82));const result=await api('/api/admin/upload',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});return result.url;}finally{bitmap.close();}
}};
