// Loopback-only development preview. Mock identity is never bundled in the hosted Worker.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const {default:worker}=await import(pathToFileURL(root+'/dist/server/index.js'));
const dir=path.join(root,'.local-data');fs.mkdirSync(dir,{recursive:true});const db=new DatabaseSync(dir+'/db.sqlite');if(!db.prepare("SELECT name FROM sqlite_master WHERE name='site_content'").get())db.exec(fs.readFileSync(root+'/drizzle/0000_fluffy_blue_shield.sql','utf8'));
const DB={prepare(sql){return{bind(...v){return{run:async()=>{const s=db.prepare(sql).run(...v);return{meta:{changes:s.changes}}},first:async()=>db.prepare(sql).get(...v)}} ,first:async()=>db.prepare(sql).get()}}};
const BUCKET={async put(key,bytes){fs.writeFileSync(dir+'/'+key,bytes)},async get(key){return fs.existsSync(dir+'/'+key)?{body:fs.readFileSync(dir+'/'+key)}:null}};
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.txt':'text/plain','.woff2':'font/woff2'};
const ASSETS={async fetch(req){let rel=decodeURIComponent(new URL(req.url).pathname);if(rel.includes('..'))return new Response('',{status:404});let file=root+'/dist/client'+rel;if(rel==='/')file+='index.html';if(!fs.existsSync(file)&&fs.existsSync(file+'.html'))file+='.html';if(!fs.existsSync(file)||!fs.statSync(file).isFile())return new Response('Not found',{status:404});return new Response(fs.readFileSync(file),{headers:{'Content-Type':types[path.extname(file)]||'application/octet-stream'}})}};
http.createServer(async(req,res)=>{try{const url='http://127.0.0.1:3026'+req.url;if(req.url.startsWith('/signin-with-chatgpt')){res.writeHead(302,{'Location':'/admin/','Set-Cookie':'local_editor=1; Path=/; HttpOnly; SameSite=Lax'});res.end();return;}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(!k.startsWith('oai-')&&v)headers.set(k,Array.isArray(v)?v.join(','):v);if(req.headers.cookie?.includes('local_editor=1')){headers.set('oai-authenticated-user-id','local-owner');headers.set('oai-authenticated-user-email','owner@localhost.test');}const parts=[];for await(const p of req)parts.push(p);const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(parts)}:{})});const response=await worker.fetch(request,{DB,BUCKET,ASSETS,ADMIN_EMAIL:'owner@localhost.test'});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){console.error(e);res.writeHead(500);res.end(String(e));}}).listen(3026,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:3026'));
